my_styles = ['background-color: rgb(255, 163, 144);', 'background-color: rgb(255, 206, 108);',
             'background-color: rgb(181, 189, 255);', 'background-color: rgb(184, 255, 222);',
             'background-color: rgb(255, 99, 101);']

practice_texts = ['Practice/text_1.txt', 'Practice/text_2.txt', 'Practice/text_3.txt', 'Practice/text_4.txt',
                  'Practice/text_5.txt', 'Practice/text_6.txt', 'Practice/text_7.txt', 'Practice/text_8.txt',
                  'Practice/text_9.txt', 'Practice/text_10.txt', 'Practice/text_11.txt', 'Practice/text_12.txt',
                  'Practice/text_13.txt', 'Practice/text_14.txt', 'Practice/text_15.txt', 'Practice/text_16.txt',
                  'Practice/text_17.txt', 'Practice/text_18.txt', 'Practice/text_19.txt', 'Practice/text_20.txt',
                  'Practice/text_21.txt', 'Practice/text_22.txt', 'Practice/text_23.txt', 'Practice/text_24.txt',
                  'Practice/text_25.txt', 'Practice/text_26.txt', 'Practice/text_27.txt', 'Practice/text_28.txt',
                  'Practice/text_29.txt', 'Practice/text_30.txt', 'Practice/text_31.txt', 'Practice/text_32.txt',
                  'Practice/text_33.txt', 'Practice/text_34.txt', 'Practice/text_35.txt', 'Practice/text_36.txt',
                  'Practice/text_37.txt', 'Practice/text_38.txt', 'Practice/text_39.txt', 'Practice/text_40.txt',
                  'Practice/text_41.txt', 'Practice/text_42.txt', 'Practice/text_43.txt', 'Practice/text_44.txt',
                  'Practice/text_45.txt', 'Practice/text_46.txt', 'Practice/text_47.txt', 'Practice/text_48.txt',
                  'Practice/text_49.txt', 'Practice/text_50.txt', 'Practice/text_51.txt', 'Practice/text_52.txt',
                  'Practice/text_53.txt', 'Practice/text_54.txt', 'Practice/text_55.txt', 'Practice/text_56.txt',
                  'Practice/text_57.txt', 'Practice/text_58.txt', 'Practice/text_59.txt', 'Practice/text_60.txt',
                  'Practice/text_61.txt', 'Practice/text_62.txt', 'Practice/text_63.txt', 'Practice/text_64.txt',
                  'Practice/text_65.txt', 'Practice/text_66.txt', 'Practice/text_67.txt', 'Practice/text_68.txt',
                  'Practice/text_69.txt', 'Practice/text_70.txt', 'Practice/text_71.txt']

practice_texts_eng = ['Practice_eng/text_1.txt', 'Practice_eng/text_2.txt', 'Practice_eng/text_3.txt',
                      'Practice_eng/text_4.txt', 'Practice_eng/text_5.txt', 'Practice_eng/text_6.txt',
                      'Practice_eng/text_7.txt', 'Practice_eng/text_8.txt', 'Practice_eng/text_9.txt',
                      'Practice_eng/text_10.txt', 'Practice_eng/text_11.txt', 'Practice_eng/text_12.txt',
                      'Practice_eng/text_13.txt', 'Practice_eng/text_14.txt', 'Practice_eng/text_15.txt',
                      'Practice_eng/text_16.txt', 'Practice_eng/text_17.txt', 'Practice_eng/text_18.txt',
                      'Practice_eng/text_19.txt', 'Practice_eng/text_20.txt', 'Practice_eng/text_21.txt',
                      'Practice_eng/text_22.txt', 'Practice_eng/text_23.txt', 'Practice_eng/text_24.txt',
                      'Practice_eng/text_25.txt', 'Practice_eng/text_26.txt', 'Practice_eng/text_27.txt',
                      'Practice_eng/text_28.txt', 'Practice_eng/text_29.txt', 'Practice_eng/text_30.txt',
                      'Practice_eng/text_31.txt', 'Practice_eng/text_32.txt', 'Practice_eng/text_33.txt',
                      'Practice_eng/text_34.txt', 'Practice_eng/text_35.txt', 'Practice_eng/text_36.txt',
                      'Practice_eng/text_37.txt', 'Practice_eng/text_38.txt', 'Practice_eng/text_39.txt',
                      'Practice_eng/text_40.txt', 'Practice_eng/text_41.txt', 'Practice_eng/text_42.txt',
                      'Practice_eng/text_43.txt', 'Practice_eng/text_44.txt', 'Practice_eng/text_45.txt',
                      'Practice_eng/text_46.txt', 'Practice_eng/text_47.txt', 'Practice_eng/text_48.txt',
                      'Practice_eng/text_49.txt', 'Practice_eng/text_50.txt', 'Practice_eng/text_51.txt',
                      'Practice_eng/text_52.txt', 'Practice_eng/text_53.txt', 'Practice_eng/text_54.txt',
                      'Practice_eng/text_55.txt']
