# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'int.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget
from PyQt5 import uic
import sys
import time

my_styles = ['background-color: rgb(255, 206, 108);', 'background-color: rgb(181, 189, 255);',
             'background-color: rgb(255, 163, 144);', 'background-color: rgb(184, 255, 222);',
             'background-color: rgb(255, 99, 101);']


class MyWidget(QMainWindow):
    #########################################################################################################
    #   БАЗА   ##############################################################################################
    #########################################################################################################
    def __init__(self):
        super().__init__()
        uic.loadUi('int.ui', self)
        # ПОЛЕ ДЛЯ ЧТЕНИЯ ТЕКСТА
        self.plainTextEdit_2.setReadOnly(True)
        # ЧЕКБОКС КЛАВИАТУРЫ
        self.show_keyboard_checkBox.stateChanged.connect(self.check_answer)
        # ДЕФОЛТНЫЙ ТЕКСТ
        self.plainTextEdit_2.setPlainText('Привет, я помогу тебе научиться печатать вслепую!')
        # РЕЖИМЫ: УРОК И ПРАКТИКА
        self.it_is_Practice = False
        self.btn_Practice.clicked.connect(self.change_mods)

        #########################################################################################################
        # ИЗМЕНЕНИЕ СТИЛЯ КЛАВИАТУРЫ ############################################################################
        #########################################################################################################
        self.main_style = 'background-color: rgb(255, 206, 108);'
        self.my_buttons = [self.btn_sth, self.btn_num_1, self.btn_num_2, self.btn_num_3,
                           self.btn_num_4, self.btn_num_5, self.btn_num_6,
                           self.btn_num_7, self.btn_num_8, self.btn_num_9,
                           self.btn_num_0, self.btn_minus, self.btn_ravno,
                           self.btn_str_1, self.btn_str_2, self.btn_str_3,
                           self.btn_str_4, self.btn_str_5, self.btn_str_6,
                           self.btn_str_7, self.btn_str_8, self.btn_str_9,
                           self.btn_str_10, self.btn_str_11, self.btn_str_12,
                           self.btn_str2_1, self.btn_str2_2, self.btn_str2_3,
                           self.btn_str2_4, self.btn_str2_5, self.btn_str2_6,
                           self.btn_str2_7, self.btn_str2_8, self.btn_str2_9,
                           self.btn_str2_10, self.btn_str2_11, self.btn_str3_1,
                           self.btn_str3_2, self.btn_str3_3, self.btn_str3_4,
                           self.btn_str3_5, self.btn_str3_6, self.btn_str3_7,
                           self.btn_str3_8, self.btn_str3_9, self.btn_str3_10,
                           self.btn_space]
        self.my_buttons_to_change_all_colors = [self.btn_sth, self.btn_num_1, self.btn_num_2,
                                                self.btn_num_4, self.btn_num_5, self.btn_num_6,
                                                self.btn_num_7, self.btn_num_8, self.btn_num_9,
                                                self.btn_num_0, self.btn_minus, self.btn_ravno,
                                                self.btn_str_1, self.btn_str_2, self.btn_str_3,
                                                self.btn_str_4, self.btn_str_5, self.btn_str_6,
                                                self.btn_str_7, self.btn_str_8, self.btn_str_9,
                                                self.btn_str_10, self.btn_str_11, self.btn_tab,
                                                self.btn_str_12, self.btn_Rshift, self.btn_Lshift,
                                                self.btn_str2_1, self.btn_str2_2, self.btn_caps,
                                                self.btn_str2_3, self.btn_str2_4, self.btn_str2_5,
                                                self.btn_str2_6, self.btn_str2_7, self.btn_str2_8,
                                                self.btn_str2_9, self.btn_str2_10, self.btn_str2_11,
                                                self.btn_str3_1, self.btn_enter, self.btn_str_13,
                                                self.btn_str3_2, self.btn_str3_3, self.btn_str3_4,
                                                self.btn_str3_5, self.btn_str3_6, self.btn_str3_7,
                                                self.btn_str3_8, self.btn_str3_9, self.btn_str3_10,
                                                self.btn_space, self.btn_str3_11, self.btn_num_3,
                                                self.btn_backspace]
        self.text_of_buttons = 'ё1234567890-=йцукенгшщзхъфывапролджэячсмитьбю. '

        self.btn_str3_11.clicked.connect(self.change_color)
        self.btn_str3_11.clicked.connect(self.show_keyboard_color_changed)
        #########################################################################################################
        #   ЗАТЕМНЕНИЕ ТЕКСТА #####################################################################
        #########################################################################################################
        self.used_buttons = []
        self.plainTextEdit.textChanged.connect(self.click_change_color)
        self.plainTextEdit.textChanged.connect(self.text_is_printed)
        self.plainTextEdit.textChanged.connect(self.wrong_text)
        self.len_of_text = 0
        self.text_in_PTE_2 = self.plainTextEdit_2.toPlainText()
        #########################################################################################################
        #   ИЗМЕНЕНИЕ ТЕКСТА PRACTICE, LESSONS ##################################################################
        #########################################################################################################
        self.practise_texts = ['Practice/text_1.txt', 'Practice/text_2.txt', 'Practice/text_3.txt']
        self.btn_Practice.clicked.connect(self.random_practice_text)
        self.btn_Practice.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Practice))
        self.btn_Lesson1.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson1))
        self.btn_Lesson2.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson2))
        self.btn_Lesson3.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson3))
        self.btn_Lesson4.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson4))
        self.btn_Lesson5.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson5))
        self.btn_Lesson6.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson6))
        self.btn_Lesson7.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson7))
        self.btn_Lesson8.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson8))
        self.btn_Lesson9.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson9))
        self.btn_Lesson10.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson10))
        self.now_text = ''

        #########################################################################################################
        # ТАЙМЕР ПРАКТИКА #######################################################################################
        #########################################################################################################
        self.btn_Practice.clicked.connect(self.create_timer)
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self.show_time)
        self.time = 0
        self.timeInterval = 1000
        ########################################################################################################

    #########################################################################################################
    # __НЕ ИЗМЕНЯТЬ__ #######################################################################################
    #########################################################################################################
    def click_change_color(self):
        changed_len = len(self.plainTextEdit.toPlainText())
        if changed_len > self.len_of_text:
            self.len_of_text += 1
            if len(self.plainTextEdit.toPlainText()):
                if self.plainTextEdit.toPlainText()[-1].isupper():
                    self.btn_Lshift.setStyleSheet("background-color: rgb(115, 115, 115);")
                    self.used_buttons.append(self.btn_Lshift)
                    threading.Timer(0.3, self.del_from_color_list).start()
                text = self.plainTextEdit.toPlainText().lower()
                if text[-1] in self.text_of_buttons:
                    for i in range(len(self.my_buttons)):
                        if self.my_buttons[i].text().lower() == (text[-1]).lower():
                            self.my_buttons[i].setStyleSheet("background-color: rgb(115, 115, 115);")
                            self.used_buttons.append(self.my_buttons[i])
                            threading.Timer(0.3, self.del_from_color_list).start()
        else:
            self.len_of_text -= 1
            self.btn_backspace.setStyleSheet("background-color: rgb(115, 115, 115);")
            threading.Timer(0.1, lambda: self.btn_backspace.setStyleSheet(self.main_style)).start()
            for button in self.my_buttons_to_change_all_colors:
                if button != self.btn_backspace:
                    button.setStyleSheet(self.main_style)
            self.used_buttons.clear()

    def del_from_color_list(self):
        if bool(self.used_buttons):
            self.used_buttons[0].setStyleSheet(self.main_style)
            del self.used_buttons[0]

    #########################################################################################################
    # ИЗМЕНЯЕТ ЦВЕТ ВСЕЙ КЛАВИАТУРЫ ПРИ НАЖАТИИИ CHANGE COLOR ###############################################
    #########################################################################################################
    def change_color(self):
        time.sleep(0.1)
        style_number = my_styles.index(self.main_style)
        if style_number + 1 <= len(my_styles) - 1:
            self.main_style = my_styles[style_number + 1]
        else:
            self.main_style = my_styles[0]
        for button in self.my_buttons_to_change_all_colors:
            button.setStyleSheet(self.main_style)

    def random_practice_text(self):
        text = random.choice(self.practise_texts)
        if text != self.now_text:
            time.sleep(0.1)
            file = open(text, encoding='utf-8')
            self.plainTextEdit_2.setPlainText(file.read())
            self.plainTextEdit.setPlainText('')
            self.now_text = text
            file.close()
        else:
            self.random_practice_text()

    def clicked_button_changes_color(self, button):
        button.setStyleSheet(self.main_style)
        threading.Timer(0.1, lambda: button.setStyleSheet('background-color: rgb(34, 34, 34);')).start()

    def check_answer(self, state):
        if state:
            self.columnView.move(100, 40)
        else:
            self.columnView.move(160, 330)

    def show_keyboard_color_changed(self):
        self.columnView.move(160, 330)
        self.show_keyboard_checkBox.setChecked(False)

    def create_timer(self):
        self.time = 0
        self.timer.start(1000)
        self.timeViewer.display(self.time)

    def show_time(self):
        self.time += 1
        self.set_timer(self.time)
        # #print(self.time)

    def set_timer(self, int_):
        self.time = int_
        self.timeViewer.display(self.time)

    def change_mods(self):
        self.it_is_Practice = True

    def text_is_printed(self):
        if self.it_is_Practice:
            if self.plainTextEdit.toPlainText() == self.plainTextEdit_2.toPlainText():
                time.sleep(0.1)
                speed = round((len(self.plainTextEdit_2.toPlainText()) / self.time) * 60, 0)
                end = ''
                if speed % 100 in (11, 12, 13, 14) or speed % 10 in (5, 6, 7, 8, 9, 0):
                    end = 'ов'
                elif speed % 10 in (2, 3, 4):
                    end = 'a'
                self.plainTextEdit_2.setPlainText(
                    f'Ваша скорость печати: {speed} символ{end} в минуту.')
                threading.Timer(1, lambda: self.plainTextEdit.setPlainText('')).start()
        else:
            if self.plainTextEdit.toPlainText() == self.plainTextEdit_2.toPlainText():
                time.sleep(0.1)
                self.plainTextEdit_2.setPlainText('Вы прошли урок!')
                threading.Timer(1, lambda: self.plainTextEdit.setPlainText('')).start()

    def wrong_text(self):
        text = self.plainTextEdit.toPlainText()
        text2 = self.plainTextEdit_2.toPlainText()
        if text != text2[:len(text)]:
            if text2 == self.text_in_PTE_2:
                self.plainTextEdit.setStyleSheet('color: rgb(255, 0, 0);')
            else:
                self.plainTextEdit.setStyleSheet('color: rgb(232, 232, 232);')
                self.text_in_PTE_2 = text2
        else:
            self.plainTextEdit.setStyleSheet('color: rgb(232, 232, 232);')
            self.btn_backspace.setStyleSheet(self.main_style)


#############################################################################################################
# ЗАПУСК #################################################################################################
############################################################################################################
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MyWidget()
    MainWindow.show()
    sys.exit(app.exec_())
