# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'int.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QGridLayout, QWidget
from PyQt5 import uic
import sys
import time

my_styles = ['background-color: rgb(255, 206, 108);', 'background-color: rgb(181, 189, 255);',
             'background-color: rgb(255, 163, 144);', 'background-color: rgb(184, 255, 222);',
             'background-color: rgb(255, 99, 101);']

practice_texts = ['Practice/text_1.txt', 'Practice/text_2.txt', 'Practice/text_3.txt', 'Practice/text_4.txt',
                  'Practice/text_5.txt', 'Practice/text_6.txt', 'Practice/text_7.txt', 'Practice/text_8.txt',
                  'Practice/text_9.txt', 'Practice/text_10.txt', 'Practice/text_11.txt', 'Practice/text_12.txt',
                  'Practice/text_13.txt', 'Practice/text_14.txt', 'Practice/text_15.txt', 'Practice/text_16.txt',
                  'Practice/text_17.txt', 'Practice/text_18.txt', 'Practice/text_19.txt', 'Practice/text_20.txt',
                  'Practice/text_21.txt', 'Practice/text_22.txt', 'Practice/text_23.txt', 'Practice/text_24.txt',
                  'Practice/text_25.txt', 'Practice/text_26.txt', 'Practice/text_27.txt', 'Practice/text_28.txt',
                  'Practice/text_29.txt', 'Practice/text_30.txt', 'Practice/text_31.txt', 'Practice/text_32.txt',
                  'Practice/text_33.txt', 'Practice/text_34.txt', 'Practice/text_35.txt', 'Practice/text_36.txt',
                  'Practice/text_37.txt', 'Practice/text_38.txt', 'Practice/text_39.txt', 'Practice/text_40.txt',
                  'Practice/text_41.txt', 'Practice/text_42.txt', 'Practice/text_43.txt', 'Practice/text_44.txt',
                  'Practice/text_45.txt', 'Practice/text_46.txt', 'Practice/text_47.txt', 'Practice/text_48.txt',
                  'Practice/text_49.txt', 'Practice/text_50.txt', 'Practice/text_51.txt', 'Practice/text_52.txt',
                  'Practice/text_53.txt', 'Practice/text_54.txt', 'Practice/text_55.txt', 'Practice/text_56.txt',
                  'Practice/text_57.txt', 'Practice/text_58.txt', 'Practice/text_59.txt', 'Practice/text_60.txt',
                  'Practice/text_61.txt', 'Practice/text_62.txt', 'Practice/text_63.txt', 'Practice/text_64.txt',
                  'Practice/text_65.txt', 'Practice/text_66.txt', 'Practice/text_67.txt', 'Practice/text_68.txt',
                  'Practice/text_69.txt', 'Practice/text_70.txt', 'Practice/text_71.txt']


class MyWidget(QMainWindow):
    #########################################################################################################
    #   БАЗА   ##############################################################################################
    #########################################################################################################
    def __init__(self):
        super().__init__()
        uic.loadUi('int.ui', self)
        # ПОЛЕ ДЛЯ ЧТЕНИЯ ТЕКСТА
        self.plainTextEdit_2.setReadOnly(True)
        # ЧЕКБОКС КЛАВИАТУРЫ
        self.show_keyboard_checkBox.stateChanged.connect(self.check_answer)
        # ДЕФОЛТНЫЙ ТЕКСТ
        self.plainTextEdit_2.setPlainText('Привет, я помогу тебе научиться печатать вслепую!')
        # РЕЖИМЫ: УРОК И ПРАКТИКА
        self.it_is_Practice = False
        self.btn_Practice.clicked.connect(self.change_mods)

        #########################################################################################################
        # ИЗМЕНЕНИЕ СТИЛЯ КЛАВИАТУРЫ ############################################################################
        #########################################################################################################
        self.main_style = 'background-color: rgb(255, 206, 108);'
        self.my_buttons = [self.btn_sth, self.btn_num_1, self.btn_num_2, self.btn_num_3, self.btn_num_4,
                           self.btn_num_5, self.btn_num_6, self.btn_num_7, self.btn_num_8, self.btn_num_9,
                           self.btn_num_0, self.btn_minus, self.btn_ravno, self.btn_str_1, self.btn_str_2,
                           self.btn_str_3, self.btn_str_4, self.btn_str_5, self.btn_str_6, self.btn_str_7,
                           self.btn_str_8, self.btn_str_9, self.btn_str_10, self.btn_str_11, self.btn_str_12,
                           self.btn_str2_1, self.btn_str2_2, self.btn_str2_3, self.btn_str2_4, self.btn_str2_5,
                           self.btn_str2_6, self.btn_str2_7, self.btn_str2_8, self.btn_str2_9, self.btn_str2_10,
                           self.btn_str2_11, self.btn_str3_1, self.btn_str3_2, self.btn_str3_3, self.btn_str3_4,
                           self.btn_str3_5, self.btn_str3_6, self.btn_str3_7, self.btn_str3_8, self.btn_str3_9,
                           self.btn_str3_10, self.btn_space]
        self.my_buttons_rus = {'ё': self.btn_sth, '1': self.btn_num_1, '2': self.btn_num_2, '3': self.btn_num_3,
                               '4': self.btn_num_4, '5': self.btn_num_5, '6': self.btn_num_6, '7': self.btn_num_7,
                               '8': self.btn_num_8, '9': self.btn_num_9, '0': self.btn_num_0, '-': self.btn_minus,
                               '=': self.btn_ravno, 'й': self.btn_str_1, 'ц': self.btn_str_2, 'у': self.btn_str_3,
                               'к': self.btn_str_4, 'е': self.btn_str_5, 'н': self.btn_str_6, 'г': self.btn_str_7,
                               'ш': self.btn_str_8, 'щ': self.btn_str_9, 'з': self.btn_str_10, 'х': self.btn_str_11,
                               'ъ': self.btn_str_12, 'ф': self.btn_str2_1, 'ы': self.btn_str2_2, 'в': self.btn_str2_3,
                               'а': self.btn_str2_4, 'п': self.btn_str2_5, 'р': self.btn_str2_6, 'о': self.btn_str2_7,
                               'л': self.btn_str2_8, 'д': self.btn_str2_9, 'ж': self.btn_str2_10, 'э': self.btn_str2_11,
                               'я': self.btn_str3_1, 'ч': self.btn_str3_2, 'с': self.btn_str3_3, 'м': self.btn_str3_4,
                               'и': self.btn_str3_5, 'т': self.btn_str3_6, 'ь': self.btn_str3_7, 'б': self.btn_str3_8,
                               'ю': self.btn_str3_9, '.': self.btn_str3_10, ' ': self.btn_space}
        self.my_buttons_eng = {'`': self.btn_sth, '1': self.btn_num_1, '2': self.btn_num_2, '3': self.btn_num_3,
                               '4': self.btn_num_4, '5': self.btn_num_5, '6': self.btn_num_6, '7': self.btn_num_7,
                               '8': self.btn_num_8, '9': self.btn_num_9, '0': self.btn_num_0, '-': self.btn_minus,
                               '=': self.btn_ravno, 'q': self.btn_str_1, 'w': self.btn_str_2, 'e': self.btn_str_3,
                               'r': self.btn_str_4, 't': self.btn_str_5, 'y': self.btn_str_6, 'u': self.btn_str_7,
                               'i': self.btn_str_8, 'o': self.btn_str_9, 'p': self.btn_str_10, '[': self.btn_str_11,
                               ']': self.btn_str_12, 'a': self.btn_str2_1, 's': self.btn_str2_2, 'd': self.btn_str2_3,
                               'f': self.btn_str2_4, 'g': self.btn_str2_5, 'h': self.btn_str2_6, 'j': self.btn_str2_7,
                               'k': self.btn_str2_8, 'l': self.btn_str2_9, ';': self.btn_str2_10, '"': self.btn_str2_11,
                               'z': self.btn_str3_1, 'x': self.btn_str3_2, 'c': self.btn_str3_3, 'v': self.btn_str3_4,
                               'b': self.btn_str3_5, 'n': self.btn_str3_6, 'm': self.btn_str3_7, ',': self.btn_str3_8,
                               '.': self.btn_str3_9, '/': self.btn_str3_10, ' ': self.btn_space}
        self.text_of_buttons = 'ё1234567890-=йцукенгшщзхъфывапролджэячсмитьбю. '
        self.all_buttons = [self.btn_sth, self.btn_num_1, self.btn_num_2, self.btn_num_4, self.btn_num_5,
                            self.btn_num_6, self.btn_num_7, self.btn_num_8, self.btn_num_9, self.btn_num_0,
                            self.btn_minus, self.btn_ravno, self.btn_str_1, self.btn_str_2, self.btn_str_3,
                            self.btn_str_4, self.btn_str_5, self.btn_str_6, self.btn_str_7, self.btn_str_8,
                            self.btn_str_9, self.btn_str_10, self.btn_str_11, self.btn_tab, self.btn_str_12,
                            self.btn_Rshift, self.btn_Lshift, self.btn_str2_1, self.btn_str2_2, self.btn_caps,
                            self.btn_str2_3, self.btn_str2_4, self.btn_str2_5, self.btn_str2_6, self.btn_str2_7,
                            self.btn_str2_8, self.btn_str2_9, self.btn_str2_10, self.btn_str2_11, self.btn_str3_1,
                            self.btn_enter, self.btn_str_13, self.btn_str3_2, self.btn_str3_3, self.btn_str3_4,
                            self.btn_str3_5, self.btn_str3_6, self.btn_str3_7, self.btn_str3_8, self.btn_str3_9,
                            self.btn_str3_10, self.btn_space, self.btn_str3_11, self.btn_num_3, self.btn_backspace,
                            self.btn_change_lang]

        self.btn_str3_11.clicked.connect(self.change_color)
        #########################################################################################################
        #   ЗАТЕМНЕНИЕ ТЕКСТА #####################################################################
        #########################################################################################################
        self.plainTextEdit.textChanged.connect(self.click_change_color)
        self.plainTextEdit.textChanged.connect(self.text_is_printed)
        self.plainTextEdit.textChanged.connect(self.wrong_text)
        self.len_of_text = 0
        self.text_in_PTE_2 = self.plainTextEdit_2.toPlainText()
        #########################################################################################################
        #   ИЗМЕНЕНИЕ ТЕКСТА PRACTICE, LESSONS ##################################################################
        #########################################################################################################
        self.btn_Practice.clicked.connect(self.random_practice_text)
        self.btn_Practice.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Practice))
        self.btn_Lesson1.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson1))
        self.btn_Lesson2.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson2))
        self.btn_Lesson3.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson3))
        self.btn_Lesson4.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson4))
        self.btn_Lesson5.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson5))
        self.btn_Lesson6.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson6))
        self.btn_Lesson7.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson7))
        self.btn_Lesson8.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson8))
        self.btn_Lesson9.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson9))
        self.btn_Lesson10.clicked.connect(lambda: self.clicked_button_changes_color(self.btn_Lesson10))
        self.now_text = ''

        #########################################################################################################
        # ТАЙМЕР ПРАКТИКА #######################################################################################
        #########################################################################################################
        self.btn_Practice.clicked.connect(self.create_timer)
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self.show_time)
        self.time = 0
        self.timeInterval = 1000
        ########################################################################################################
        self.btn_Practice.clicked.connect(lambda: self.click_change_color(practice_or_lesson=True))
        ########################################################################################################
        self.btn_change_lang.clicked.connect(self.change_lang)
        self.now_lang = 'rus'

    #########################################################################################################
    # __НЕ ИЗМЕНЯТЬ__ #######################################################################################
    #########################################################################################################
    def change_lang(self):
        if self.now_lang == 'rus':
            for letter in self.my_buttons_eng:
                self.my_buttons_eng[letter].setText(letter.upper())
            self.now_lang = 'eng'
            self.btn_change_lang.setText('Рус. раскалдка')
        elif self.now_lang == 'eng':
            for letter in self.my_buttons_rus:
                self.my_buttons_rus[letter].setText(letter.upper())
            self.now_lang = 'rus'
            self.btn_change_lang.setText('Англ. раскалдка')

    def click_change_color(self, practice_or_lesson=False):
        text_in_pte = self.plainTextEdit.toPlainText()
        old_len = self.len_of_text
        self.len_of_text = len(text_in_pte)
        if self.len_of_text > old_len:
            if text_in_pte[-1].isupper():
                self.turn_gray_and_return(self.btn_Lshift)
            text_in_pte_lower = text_in_pte.lower()
            if self.now_lang == 'rus':
                for letter in self.my_buttons_rus:
                    if letter == text_in_pte_lower[-1]:
                        self.turn_gray_and_return(self.my_buttons_rus[letter])
        else:
            if not practice_or_lesson:
                self.turn_gray_and_return(self.btn_backspace)
            else:
                self.btn_backspace.setStyleSheet(self.main_style)

    def turn_gray_and_return(self, button):
        button.setStyleSheet("background-color: rgb(115, 115, 115);")
        threading.Timer(0.3, lambda: button.setStyleSheet(self.main_style)).start()

    #########################################################################################################
    # ИЗМЕНЯЕТ ЦВЕТ ВСЕЙ КЛАВИАТУРЫ ПРИ НАЖАТИИИ CHANGE COLOR ###############################################
    #########################################################################################################

    def change_color(self):
        self.columnView.move(160, 330)
        self.show_keyboard_checkBox.setChecked(False)
        time.sleep(0.1)
        style_number = my_styles.index(self.main_style)
        if style_number + 1 <= len(my_styles) - 1:
            self.main_style = my_styles[style_number + 1]
        else:
            self.main_style = my_styles[0]
        for button in self.all_buttons:
            button.setStyleSheet(self.main_style)

    def random_practice_text(self):
        text = random.choice(practice_texts)
        if text != self.now_text:
            time.sleep(0.1)
            file = open(text, encoding='utf-8')
            self.plainTextEdit_2.setPlainText(file.read())
            self.plainTextEdit.setPlainText('')
            self.len_of_text = 0
            self.now_text = text
            file.close()
        else:
            self.random_practice_text()

    def clicked_button_changes_color(self, button):
        button.setStyleSheet(self.main_style)
        threading.Timer(0.1, lambda: button.setStyleSheet('background-color: rgb(34, 34, 34);')).start()

    def check_answer(self, state):
        if state:
            self.columnView.move(100, 40)
        else:
            self.columnView.move(160, 330)

    def create_timer(self):
        self.time = 0
        self.timer.start(1000)
        self.timeViewer.display(self.time)

    def show_time(self):
        self.time += 1
        self.set_timer(self.time)
        # #print(self.time)

    def set_timer(self, int_):
        self.time = int_
        self.timeViewer.display(self.time)

    def change_mods(self):
        self.it_is_Practice = True

    def text_is_printed(self):
        if self.it_is_Practice:
            if self.plainTextEdit.toPlainText() == self.plainTextEdit_2.toPlainText():
                time.sleep(0.1)
                speed = round((len(self.plainTextEdit_2.toPlainText()) / self.time) * 60, 0)
                end = ''
                if speed % 100 in (11, 12, 13, 14) or speed % 10 in (5, 6, 7, 8, 9, 0):
                    end = 'ов'
                elif speed % 10 in (2, 3, 4):
                    end = 'a'
                self.plainTextEdit_2.setPlainText(
                    f'Ваша скорость печати: {speed} символ{end} в минуту.')
                threading.Timer(1, lambda: self.plainTextEdit.setPlainText('')).start()
                self.timer.stop()
                self.time = 0
                self.len_of_text = 0
        else:
            if self.plainTextEdit.toPlainText() == self.plainTextEdit_2.toPlainText():
                time.sleep(0.1)
                self.plainTextEdit_2.setPlainText('Вы прошли урок!')
                threading.Timer(1, lambda: self.plainTextEdit.setPlainText('')).start()
                self.len_of_text = 0

    def wrong_text(self):
        text = self.plainTextEdit.toPlainText()
        text2 = self.plainTextEdit_2.toPlainText()
        if text != text2[:len(text)]:
            if text2 == self.text_in_PTE_2:
                self.plainTextEdit.setStyleSheet('color: rgb(255, 0, 0);')
            else:
                self.plainTextEdit.setStyleSheet('color: rgb(232, 232, 232);')
                self.text_in_PTE_2 = text2
        else:
            self.plainTextEdit.setStyleSheet('color: rgb(232, 232, 232);')


#############################################################################################################
# ЗАПУСК #################################################################################################
############################################################################################################
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MyWidget()
    MainWindow.show()
    sys.exit(app.exec_())
